name: Validate University Data

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  validate-unis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.4

      - name: Install Dependencies
        run: pnpm install

      - name: Validate University Data
        run: pnpm run validate-unis
